/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    String operação="";
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtBNumero1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtBNumero2 = new javax.swing.JTextField();
        BtoSoma = new javax.swing.JButton();
        BtoSubtracao = new javax.swing.JButton();
        BtoDivisao = new javax.swing.JButton();
        BtoMultiplicacao = new javax.swing.JButton();
        TxtBResultado = new javax.swing.JTextField();
        BtoResultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1° Número:");

        jLabel2.setText("2° Número:");

        BtoSoma.setText("+");
        BtoSoma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtoSomaMouseClicked(evt);
            }
        });
        BtoSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoSomaActionPerformed(evt);
            }
        });

        BtoSubtracao.setText("-");
        BtoSubtracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtoSubtracaoMouseClicked(evt);
            }
        });

        BtoDivisao.setText("/");
        BtoDivisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtoDivisaoMouseClicked(evt);
            }
        });

        BtoMultiplicacao.setText("*");
        BtoMultiplicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtoMultiplicacaoMouseClicked(evt);
            }
        });

        BtoResultado.setText("Resultado");
        BtoResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtoResultadoMouseClicked(evt);
            }
        });
        BtoResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtBNumero1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(TxtBResultado)
                        .addGap(18, 18, 18)
                        .addComponent(BtoResultado))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(BtoSoma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtoSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtoDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtoMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TxtBNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtBNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtBNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtoSubtracao)
                    .addComponent(BtoDivisao)
                    .addComponent(BtoMultiplicacao)
                    .addComponent(BtoSoma))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtoResultado))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtoSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtoSomaActionPerformed

    private void BtoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtoResultadoActionPerformed

    private void BtoSomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtoSomaMouseClicked
        /*double numero1 = Double.parseDouble(TxtBNumero1.getText());
        double numero2 = Double.parseDouble(TxtBNumero2.getText());
        double resultado = numero1 + numero2;
        TxtBResultado.setText(Double.toString(resultado));
        System.out.println("quero somar: " + numero1);*/
        operação="+";
    }//GEN-LAST:event_BtoSomaMouseClicked

    private void BtoResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtoResultadoMouseClicked
        double numero1 = Double.parseDouble(TxtBNumero1.getText());
        double numero2 = Double.parseDouble(TxtBNumero2.getText());
        double resultado;
        calcular calc = new calcular();
        switch (operação) {
            case "+":
                resultado = calc.Somar(numero1, numero2);
                break;
                
            case "-":
                resultado = calc.subtrair(numero1, numero2);
                break;
                
            case "/":
                resultado = calc.Dividir(numero1, numero2);
                break;
                
            case "*":
                resultado = calc.Multiplicar(numero1, numero2);
                break;
                
            default:
                    JOptionPane.showMessageDialog(rootPane, "Escolha uma operação");
                throw new AssertionError();
        }
       operação="";
        TxtBResultado.setText(Double.toString(resultado));
    }//GEN-LAST:event_BtoResultadoMouseClicked

    private void BtoSubtracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtoSubtracaoMouseClicked
        operação="-";
    }//GEN-LAST:event_BtoSubtracaoMouseClicked

    private void BtoDivisaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtoDivisaoMouseClicked
        operação="/";
    }//GEN-LAST:event_BtoDivisaoMouseClicked

    private void BtoMultiplicacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtoMultiplicacaoMouseClicked
        operação="*";
    }//GEN-LAST:event_BtoMultiplicacaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtoDivisao;
    private javax.swing.JButton BtoMultiplicacao;
    private javax.swing.JButton BtoResultado;
    private javax.swing.JButton BtoSoma;
    private javax.swing.JButton BtoSubtracao;
    private javax.swing.JTextField TxtBNumero1;
    private javax.swing.JTextField TxtBNumero2;
    private javax.swing.JTextField TxtBResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
